apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-analyzer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crypto-analyzer
  template:
    metadata:
      labels:
        app: crypto-analyzer
    spec:
      containers:
        - name: crypto-analyzer
          image: <dockerhub-username>/crypto-analyzer:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"