apiVersion: v1
kind: Service
metadata:
  name: crypto-analyzer-service
spec:
  selector:
    app: crypto-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer